### ISSUE TITLE
Рисование, как залог успешного развития станции

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#10]
Ну, добавили холсты и мольберты, но нигде кроме техов их не найти, предлагаю в Pet Store поставить один/два мольберта, и добавить стол, положить на него различных холстов. А то творчества не будет на станции.

**Comment by Artem0410** [comment]
О. На станции есть рисование?

**Comment by Dydna** [comment]
@Artem0410 Да,в техах есть мольберты, но само рисование крайне муторное и для комфортного рисования требует приближение экрана.

**Comment by ITBlackwood** [comment]
Добавил мольберты в комнату отдыха на стол.
