### ISSUE TITLE
Перчатки дутуктивов [Реквест]

### ISSUE THREAD

**Issue by Artem0410** [ITBlackwood/ATMTA-Station#102]
В чем дело. Перчатки у бедных детективов не очень удобны. Дело в том, что они оставляют частицы на уликах. Тоже самое относится и к одежде дутуктивов.

Я щитаю, что перчатки НЕ должны оставлять частиц.

**Comment by ITBlackwood** [comment]
Смотри PR №7506 парадайзов.
