### ISSUE TITLE
Камера в дормах

### ISSUE THREAD

**Issue by ZergNyxx** [ITBlackwood/ATMTA-Station#103]
Камера в Криодормах  называется Mr. Chang's.

![default](https://user-images.githubusercontent.com/18599420/26973545-bc2cb67e-4d1f-11e7-9f89-9ece5eefd8c0.png)

**Comment by ITBlackwood** [comment]
Постоянно забываю ее переименовать.

**Comment by ITBlackwood** [comment]
Исправлено
