### ISSUE TITLE
ОПТИМИЗАЦИЯ

### ISSUE THREAD

**Issue by sswwyyaatt** [ITBlackwood/ATMTA-Station#107]
**Описание проблемы**:
Суть проблемы в отсутствии оптимизации

**Что должно было произойти**: 
Она должна была быть

**Что произошло вместо этого**:
На неё был положен хуй

**Почему это плохо/Какие последствия этого:**
Хуле всё как в слоумоушене, это пиздец жи

**Детальное описание как повторить возникновение проблемы**:
Взять билд, насрать в него, забыть убрать какахи

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Нам уже ничего не поможет

**Comment by ITBlackwood** [comment]
Дядя Свят, с этим ничего не поделать. Не верьте в сказки, оптимизация - це миф.
