### ISSUE TITLE
СУПЕР ВАЖНОСТЬ БЛЯТЬ С ВАШИМИ НОВЫМИ ВКУСАМИ 

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#110]
http://prntscr.com/fiwx5d ВОТ БЛЯТЬ ЕШЬ ПЛАСТЫРЬ! ЕШЬ ЕГО СУКА!

**Comment by ITBlackwood** [comment]
Я понимаю твою ярость но
ЗАГОЛОВОК
ОПИСАНИЕ. 

ПОЖАЛУЙСТА.

**Comment by ITBlackwood** [comment]
ИЛЬЯ ЧИНИ.
Ты ввел вкусы, этот Ишшу на твоей совести
