### ISSUE TITLE
Ракеты мехов.

### ISSUE THREAD

**Issue by ZergNyxx** [ITBlackwood/ATMTA-Station#111]
**Описание проблемы**:
После выстрела ракетами меха, они остаются в воздухе. Их можно взять, и кидать как копья, при этом взрывая лица.

**Что должно было произойти**: 
Ракета должна была улететь.

**Что произошло вместо этого**:
Она зависла в воздухе.

**Почему это плохо/Какие последствия этого:**
Как будто это надо объяснять.(Ловить ракеты руками, мам, смотри)

**Детальное описание как повторить возникновение проблемы**:
Создать боевого меха, поставить ракетную установку, выстрелить.

**Comment by ITBlackwood** [comment]
Больше инфы надо.
Что за мех
Какие ракеты
Какой з-лвл в конце концов

**Comment by ZergNyxx** [comment]
Любой боевой. (Гигакс\Дюранд\Мародер\Фазон)
SRM-8 missile rack
Станция\ЦК

**Comment by ITBlackwood** [comment]
Во всём виноват ебучий мув-рефактор. 
Я в душе не ебу как это чинить. Серьезно. Вот правда.

**Comment by ghost** [comment]
Посмотреть как летают пули

**Comment by ITBlackwood** [comment]
@outbools За исключением того что пули после выстрела - это прожектайлы, а ракеты после выстрела... Брошенные айтемы!

**Comment by ZergNyxx** [comment]
Томушо у нас прожектайлов ракет нет? А ещё арбалет кидается палками, а не стреляет.

**Comment by ghost** [comment]
НУ И ТУПИЗНА

**Comment by ghost** [comment]
кстати сюрприз - прожектайлы тоже брошенные вещи

**Comment by ghost** [comment]
https://github.com/ParadiseSS13/Paradise/pull/7780
