### ISSUE TITLE
Ребаланс Пода синдиката

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#118]
Проведя многочисленные (нет) исследования, выяснили, что под синдиката, а именно его турели почти полностью неуязвимы, их можно уничтожить только с помощью xray лазер гана, либо взорвав бомбу , достаточно мощную, чтобы она снесла двери(тогда турелям точно пизда). Не думаю, что при внезапно начавшемся пиздеце экипаж будет подтаскивать к поду бомбы с фуелтанками(да и идея не очень), ведь кроме турелей в нём есть оперативники. Это нужно нерфить, либо повышением цены активатора пода, либо его выпиливанием, либо сделать конструкцию таковой, чтобы турели располагались на флуртайтрах/чем то ещё, но не на стенах, чтобы их можно было уничтожить обычным оружием. До этого был ишшус, что они никак не дамажатся ионкой, https://github.com/ITBlackwood/ATMTA-Station/issues/50 , и вроде как, они до сих пор ей не дамажатся.

**Comment by ITBlackwood** [comment]
Хорошо, постараюсь придумать что-нибудь

**Comment by ZergNyxx** [comment]
Как будто у нас нюка вообще бывает. И контрятся они баком с водой.

**Comment by ghost** [comment]
Бля нюка с подом эта инставин просто из-за внезапности

**Comment by ITBlackwood** [comment]
Изменил density стен пода на которых крепятся турели. Этого достаточно
