### ISSUE TITLE
It's time to stop

### ISSUE THREAD

**Issue by MsCounterMax** [ITBlackwood/ATMTA-Station#119]
**Описание проблемы**:
Жирнороль спиздила золотую карту и набила тазерами рюкзак? Косорукие инженеры не заварили венты, дав возможность паукам заовнить станцию, 2 сквада ЕРТшников и детсад? Из ксенки выбежала квина с телом ксенобиолога и начала запиливать яйца прямо в коридоре? Из гейтвея вылезло пару статуй которые начали наваливать всем вышеперечисленным? Не проблема для шахтёра, регенящегося от сердец аки ёбаный Росомаха. Сломанные руки и ноги не проблема для нашего доблестного уроженца Каргонии, любая беда будет оперативно отхуярена ногами, а все раненные смогут отрастить руки, ноги, даже органы и иногда даже головы, и не один раз! Хайль Каргония! (Услуги наших сотрудников не распространяются на сбежавшую сингулярность и педальные гибы)

**Что должно было произойти**: 
Станция не уследила — станция обосралась. В ЕРТ набрали криворуких дшек — ЕРТ обосрались. Бетмены из карго должны быть таковыми только на астеройде, а не на станции, осыпая всех реджувами как Иисус Новой Эры.

**Что произошло вместо этого**:
СЛАВНАЯ ПОБЕДА КАРГОНИИ

**Почему это плохо/Какие последствия этого:**
Очевидное поощрение повергейминга (особенно рольханта), потому что если ты можешь себя реджувить по щелчку пальцев, ты так или иначе будешь танковать ебалом всё, что безопаснее синги. И, сука, помогать танчить ебалом всем вокруг.

**Детальное описание как повторить возникновение проблемы**:
СТАТЬ ГЛОКЕРОМ

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Вот буквально только что Вожач нащитспавнил разлом, и до кучи вайнов, спавнящих цветки, и метеориты. Конечно выжившие пошли стукать, а шахтёр снабдил их аптечками набитыми сердцами. Конечно щитспавн был нейтрализован, а количество сломанных и реджувнутых конечностей стремится к бесконечности. И так каждый день.

И у меня есть идеи, как эту хуйню нерфить, например обыкновенный передоз, который тригерит образование сарина, если кто-нибудь жрёт сердца с частотой в 5 минут и менее. Или просто урон 75 токсинами, а при попытке отхилить токсины сердцем, урон уже не 75 а 90.

**ПРОСТО СДЕЛАЙТЕ УЖЕ С ЭТИМ ЧТО-НИБУДЬ ААААААААА**

**Comment by ITBlackwood** [comment]
Достаточно было написать "Понерфите сердца хайвлордов"

По теме: Скоро лаваленд, а значит хайвлорды уйдут в нахуй.
