### ISSUE TITLE
Дырочка в мед. бее.

### ISSUE THREAD

**Issue by MrFoxik** [ITBlackwood/ATMTA-Station#12]
**Описание проблемы**:
Дырка в мед. бее, если будет разгерма она не защитит.

**Что должно было произойти**: 
Там должен быть фаерлок.

**Что произошло вместо этого**:
Его нет. > http://piccy.info/view3/11026436/5d166824aa899214d4a5dfd2e70ddfb8/

**Почему это плохо/Какие последствия этого:**
Все медики и их пациенты умрут из-за этого.

**Детальное описание как повторить возникновение проблемы**:
Зайти на сервер, посмотреть на дырочку в мед. бее

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Умершим медикам и их пациентам уже ничто не поможет.

**Comment by ITBlackwood** [comment]
Дырка убрана.
