### ISSUE TITLE
Late AI join

### ISSUE THREAD

**Issue by Dankorsar** [ITBlackwood/ATMTA-Station#120]
Частенько случается так, что ИИ заходит в раунд очень поздно. К этому времени и закуп трейторов соответствующий, и пленники в подсобках, и парочки в дормах. И тут вдруг появляется то, что может найти тебя где угодно и заблочить там, а то и сжечь вообще. И надо спецом идти, переделывать его под себя... Если, конечно, выйдет.
Идея состоит в том, чтобы запретить вход за ИИ, начиная с определённого времени (от десяти минут до получаса). Выйдет в некотором роде и подготовка для персонала, на который, возможно, не будут охотиться в течении этого времени, и не будет из-за этого ерунды у трейторов.

**Comment by Dydna** [comment]
Трейторы тянут с выполнением обжетивов и оставляют свидетелей? Это их траблы, а ИИ очень часто нужен станции поэтому считаю, что твоё предложение - говно.

**Comment by ITBlackwood** [comment]
Согласен со смаелом. 

К тому же, как ты объяснишь невозможность загрузки ИИ через определенное к-во времени?
ЯДРО СГНИЛО? Вряд ли.
