### ISSUE TITLE
Электроника для шлюзов

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#121]
**Описание проблемы**:
Airlock electronics нельзя ограничивать по доступу

**Что должно было произойти**: 
Когда я провел картой я должен был бы выбрать на какой доступ ограничить.

**Что произошло вместо этого**:
Не Swipe ID в меню Airlock electronics не просто кликанье картой на электронику не работало

**Почему это плохо/Какие последствия этого:**
Если нужно будет делать дверь с ограниченным доступом то это только через РЦД.

**Детальное описание как повторить возникновение проблемы**:
Взять в руку электронику в другую карту, нажать на электронику появится окно, и пытаться что-то сделать

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Шеф, секрет, не было роли.

**Comment by ITBlackwood** [comment]
Доступ аирлоков в платах можно настраивать только с инженерным доступом.
