### ISSUE TITLE
Нерф Ревенанта

### ISSUE THREAD

**Issue by Lianovskiy** [ITBlackwood/ATMTA-Station#123]
**Описание проблемы**:
В переапанности Ревенанта.

**Что должно было произойти**: 
Ревенант должен быть понерфлен!

**Что произошло вместо этого**:
произошло то, что его способность не только валит на пол и наносит урон, но ещё и не даёт ни уйти из под атаки ни погнаться за ним и выдать пиздюлин

**Почему это плохо/Какие последствия этого:**
Баланс страдает в пользу антага, которого нельзя убить без лазерного дальнобойного оружия, ведь за ним невозможно угнаться. Да и убежать невозможно. В итоге он закликивает вас этой способностью насмерть.

**Детальное описание как повторить возникновение проблемы**:
Вызвать ревенанта, сожрать 5 трупов, кликать по бедному экипажу до победного.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Режим - генокрад.

**Comment by Dydna** [comment]
С ящуром забили кулаками насмерть ревенанта, за что я получил бан, так что всё вполне реально, он достаточно ватный, а вы должны просто держаться подальше от лампочек, или вообще их вынимать, и ходить в 2-3 ебала, почти никакой угрозы он не представляет, главное вовремя убрать мартышек и трупы дшек.

**Comment by Wojach** [comment]
Догнать его можно, а падали вы потому что дали себя пробить атаками по 5 токсин урона, когда топтались возле ботаники.

**Comment by ITBlackwood** [comment]
Ревенант находится в сбалансированном состоянии. Нечего там нерфить.
