### ISSUE TITLE
Увеличение пожароопасности

### ISSUE THREAD

**Issue by Lianovskiy** [ITBlackwood/ATMTA-Station#124]
**Описание проблемы**:
На станции почти никогда не случается каких-либо серьёзных происшествий в виде пожаров.

**Что должно было произойти**: 
Всё должно гореть синим пламенем. Пол, стены, потолок и даже ассистенты!

**Что произошло вместо этого**:
Вместо этого нихуя не горит.

**Почему это плохо/Какие последствия этого:**
НА СТАНЦИИ ПИЗДЕЦ СКУЧНО, А ПРОСИТЬ ПЕДАЛЕЙ НАЩИТСПАВНИТЬ - СЕБЕ ДОРОЖЕ

**Детальное описание как повторить возникновение проблемы**:
По моему мнению на станции мало предметов приводящих к возгоранию, а не ко взрыву. Бросить окурок на пол, в итоге нихуя.

**Comment by sswwyyaatt** [comment]
Двачую кстати, может даже правда пофановей будет

2 июля 2017 г. 15:02 пользователь "Lianovskiy" <notifications@github.com>
написал:

**Comment by ITBlackwood** [comment]
Не могу не согласиться. Я тоже давно говорю про эту проблему - у станции куча средств для устранения пожаров - Атмосферники, Огнетушители на каждом шагу, даже специальный мех , но сами пожары попросту не случаются. Взрыв фуелтанка? Хуета - погорит секунду и потухнет само. 
Что тушить то? Турбину? Пиро аномалии? Сигареты во рту бармена? 

Когда вообще огнетушители использовались кем-то кроме ксенобиологов по назначению?

**Comment by Dydna** [comment]
Ну бло, если тебе бутылкой по ебасосу дали и подожгли, то кататься ты не будешь.

**Comment by ITBlackwood** [comment]
Это даже не пожар, если подожгли моба.

**Comment by Dydna** [comment]
ну блять, можно добавить какое то самовозгорание в трубах, но хуй знает как, и как это объяснить

**Comment by ITBlackwood** [comment]
Я давно предлагал закодить рандом ивент с пожаром в каком-либо из отсеков.

**Comment by ghost** [comment]
Там есть какая то надстройка в конфиге на пожары

**Comment by ghost** [comment]
#140 в стадии теста - закрою после мержа
