### ISSUE TITLE
Борги и мезонки

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#128]
**Описание проблемы**:
При активированных мезонках у борга при смене модуля они не пропадают, даже если поддержка мезонок у ногового модуля отсутствует

**Что должно было произойти**: 
Борг с новым модулем не должен видеть всё в мезонках

**Что произошло вместо этого**:
Он видит всё в мезонках.

**Почему это плохо/Какие последствия этого:**
Немного дисбаланса, и часто бьёт по глазам, особенно, если тебя сменили на охранный.

**Comment by fadedDexofan** [comment]
@Dydna [Фикс](https://github.com/ITBlackwood/ATMTA-Station/commit/79050120cc2ddd61a19d889092da0173ad9203f9)

**Comment by ghost** [comment]
Закрыто https://github.com/ITBlackwood/ATMTA-Station/commit/79050120cc2ddd61a19d889092da0173ad9203f9
