### ISSUE TITLE
Вилка (Спрайт)

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#13]
1 Описание проблемы:
У вилки серый мертвый пиксель.
2 Что должно было произойти: 
Ничего не должно было появиться.
3 Что произошло вместо этого:
Появился серый, мертвый пиксель.
4 Детальное описание как повторить возникновение проблемы:
Взять вилку.
![default](https://cloud.githubusercontent.com/assets/15972245/24611880/3a4cfbe0-188c-11e7-827e-c25bc724a127.PNG)

**Comment by ITBlackwood** [comment]
Проверил inhands спрайты вилки - на них нет мертвых пикселей. Причина в чем-то другом.

**Comment by ITBlackwood** [comment]
Зато в правой руке некорректно отображалось. Исправил.
