### ISSUE TITLE
Как нарушить сопы из-за механа:пособие.

### ISSUE THREAD

**Issue by MrDiamond320** [ITBlackwood/ATMTA-Station#130]
Главы не могут в поднятие кода без педольной магии или карты кэпа.Это заставляет взламывать кэпскую или просить педолей.А если карту украли ассистенты а педали спят?Так вот.Запилить главам возможность менять код,ибо когда Пшшшшшш(Педоль) нарушает сопы ибо "Я не могу за ХоС-а сменить код" то это уже пиздец,товарищи.

**Comment by Dydna** [comment]
Подтверждаю, даже ебаный Хос не может сменить код на синий. Всем ебучим главам нужно дать возможность повышать код и/или связываться с цк, ибо это может делать только АВД, капитан через консоль со своим доступом и магистрат.

**Comment by fadedDexofan** [comment]
[Фикс](https://github.com/ITBlackwood/ATMTA-Station/pull/139)

**Comment by ghost** [comment]
Закрыто https://github.com/ITBlackwood/ATMTA-Station/pull/139
