### ISSUE TITLE
Постеры

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#137]
**Описание проблемы**:
У постеров сломались спрайтики и описания. Но это произошло не со всеми постерами

**Что должно было произойти**: 
Они не должны были ломаться

**Что произошло вместо этого**:
Ну сами гляньте, ёбана 
![image](https://user-images.githubusercontent.com/24633360/28075488-4ed090d8-6664-11e7-95ca-8756c5e8f332.png) 
![image](https://user-images.githubusercontent.com/24633360/28075500-54a501e2-6664-11e7-8c00-1cf60208a969.png)

**Почему это плохо/Какие последствия этого:**
Режет глазки и нет атмосфееры

**Детальное описание как повторить возникновение проблемы**:
Посмотрите на постеры.

**Comment by fadedDexofan** [comment]
@Dydna [Фикс](https://github.com/ITBlackwood/ATMTA-Station/pull/139)
