### ISSUE TITLE
Возможность выпить спермы

### ISSUE THREAD

**Issue by Lianovskiy** [ITBlackwood/ATMTA-Station#145]
**Описание проблемы**:
Сперму нельзя заскупить в стакан

**Что должно было произойти**: 
Вся сперма, оставшаяся на полу, должна быть заскуплена в стакан!

**Что произошло вместо этого**:
Вместо этого мы теряем множество возможностей пилить напитки и еду из спермы. Ну и поить спермой смайлов.

**Почему это плохо/Какие последствия этого:**
Потому что так не фаново.

**Comment by ITBlackwood** [comment]
God left.
