### ISSUE TITLE
я пидор

### ISSUE THREAD

**Issue by Lianovskiy** [ITBlackwood/ATMTA-Station#146]
**Описание проблемы**:
я пидор

**Что должно было произойти**: 
я ебу баб

**Что произошло вместо этого**:
я сосу хуи у слаймов

**Почему это плохо/Какие последствия этого:**
быть пидором некошерно

**Детальное описание как повторить возникновение проблемы**:
1.будьте пидором
2.лягьте на пол
3.заплачьте

**Comment by Valnaver** [comment]
А в идеале спиздить систему списанной с моей реальной жизни где я вроде пидор а вроде нет

**Comment by Dydna** [comment]
И сделать третий гендер: "Кирюха Карманный", чтобы точно ебануться можно было.

**Comment by ghost** [comment]
Хм вряд ли мы починим твое пидорство братан
