### ISSUE TITLE
БАГ ТРУБ

### ISSUE THREAD

**Issue by Lianovskiy** [ITBlackwood/ATMTA-Station#15]
**Описание проблемы**:
Трубы всё так же пропадают из поля зрения при прикручивании к полу

**Что должно было произойти**: 
Они не должны пропадать из поля зрения

Речь идёт об трубах атмосферы.

**Comment by ITBlackwood** [comment]
Датум отвечающий за иконки не определяет для "standalone", т.е. одиночной трубы спрайт, до тех пор пока к ней не будет присоединена еще одна труба. Технически, все работает одновременно и так как надо, и нихрена неправильно. Пофиксить я не смог.

**Comment by ghost** [comment]
https://github.com/ParadiseSS13/Paradise/pull/6693

>Our atmos pipes don't really support being put on the map as a fitting, so I've just removed it as fixing this issue would not be worth the effort.
