### ISSUE TITLE
Космо-травматы для СБ

### ISSUE THREAD

**Issue by x0xoL** [ITBlackwood/ATMTA-Station#164]
хочется видеть в родном сб, чтобы в шкафчиках были травматы - не только тазеры. чтобы сб при должном сопротивление могли бы убить преступника ( шанс при попадание в голову ) или ранить серьёзно. желательно, чтобы пистолет стрелял именно резиновыми пулями

**Comment by ghost** [comment]
Заказывай травмат в карго - называется Enforcer
