### ISSUE TITLE
Ресуплай ЕРТ.

### ISSUE THREAD

**Issue by PESMONKARASIK** [ITBlackwood/ATMTA-Station#18]
Описание проблемы:
Нынешние ЕРТ совершенно беспомощны перед рядом проблем. Даже тритор с двойным лазмечом может вырезать батальон ЕРТ.

Что должно было произойти:
Произойти замена снаряжения ЕРТ гамма-сквада почти полностью. И немного улучшить снаряжение секьюрити ЕРТ красного кода.

Нужны энергетические щиты гамма-ерт.
По 1 в рюкзак. Путь к щиту.
/obj/item/weapon/shield/energy
Пульсач-пистолет оставляем только командиру. От пульсачей слишком большие повреждения. Даже реактивный гранатомёт дыры не делает. Просто плитку повреждает и бьёт сплешом. 
Командору его выдадим в руки. И 3 ракеты. Лишняя пара наручников не нужна. Она отдельно лежит зачем-то.
Путь к ракетомёту и ракеткам.
/obj/item/weapon/gun/rocketlauncher
/obj/item/ammo_casing/rocket
Медику и инженеру лазкарабины и по 3 обоймы.
Пути
/obj/item/weapon/gun/projectile/automatic/lasercarabine
/obj/item/ammo_box/magazine/laser
Инженеру меняем обычные инсулярки на боевые перчатки.
Путь к ним.
/obj/item/clothing/gloves/combat
У бойца гаммы-ЕРТ, который секьюрити, отбираем пульсач-карабин из рук. Даём ARG в рюкзак. И дробовик в руки. 
Путь к штурмовой винтовке АРГ и патрончикам. 3 обоймы в рюкзак и 2 в карманы.
/obj/item/weapon/gun/projectile/automatic/ar
/obj/item/ammo_box/magazine/m556
Путь к дробовику и к 2 коробочкам патронов в рюкзак.
/obj/item/weapon/gun/projectile/shotgun/automatic/combat
/obj/item/ammo_box/shotgun/buck

По поводу ЕРТ красного кода. Добавить бойцам (секьюрити) щит риот в руки, пистолет стечкина и 2 обоймы от него в карманы.
Щит риот.
/obj/item/weapon/shield/riot
Пистолет стечкина и обоймы.
/obj/item/weapon/gun/projectile/automatic/pistol
/obj/item/ammo-box/magazine/m10mm

**Comment by Dydna** [comment]
Можно дать вместо риот щита телескопик, и в рюкзак его. Путь я вам не скажу( я не про круглый щит, как у эскадрона смерти)

**Comment by PESMONKARASIK** [comment]
Телескопик защищает далеко не от всего. И от того, чего защищает, спасает только с достаточно малым шансом.

**Comment by ITBlackwood** [comment]
Запилил
