### ISSUE TITLE
СПУ и их конечности

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#19]
когда суммарный урон по конечностям CПУ превышает определённый порог, выкидывает его в крит, то есть у тебя две конечности моргают красным и ты уже в крите, но ведь все необходимые для существования модули в груди, и урон конечностям вообще не должен влиять на сознание спу 
( Пожелания Альфы)

**Comment by ITBlackwood** [comment]
Я вообще боюсь лезть в код СПУ.
Вряд ли смогу решить такую проблему, но попытаюсь.

**Comment by ITBlackwood** [comment]
К сожалению тут я бессилен.
