### ISSUE TITLE
Скреллам нужен секс

### ISSUE THREAD

**Issue by tommehy** [ITBlackwood/ATMTA-Station#192]
**Описание проблемы**:
У скреллов нет ни ануса, ни рабочих тентаклей на голове для трахания

**Что должно было произойти**: 
В анус можно пихать письки, щупла и дильды, тентаклями можно там ебать.

**Что произошло вместо этого**:
Абсолютная девственность.

**Почему это плохо/Какие последствия этого:**
Скрелл хочет ерпшить через интеракты и не может он становится хуманм это плохо

**Детальное описание как повторить возникновение проблемы**:
Найти Смаела за скрелла, попросить его секс, понять, что у вас не будет секса

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
НАМ НИЧТО НЕ ПОМОЖЕТ САМОЕ ВРЕМЯ ИДТИ ФИККСИТЬ АПРАРВЛЛВЛАЛОВОСЬ

**Comment by tommehy** [comment]
ща сделаем пуллреквест падажжите

**Comment by Dydna** [comment]
Я ебал драска играя за краба, если ты попросил у смайла секс- у вас будет секс.
