### ISSUE TITLE
recharger и голубой щит

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#2]
У блющилда энергетическое оружие, но recharger'а у него в кабинете нет, как и офицерского доступа. Единственное место, где он может зарядить свой ган - мостик.Я думаю что в кабинет блющилда стоит добавить recharger.

**Comment by ITBlackwood** [comment]
Окей

**Comment by ITBlackwood** [comment]
Добавил настенный речарджер тебе за щеку проверяй
