### ISSUE TITLE
Вещи из спавнсписка

### ISSUE THREAD

**Issue by Raspupir** [ITBlackwood/ATMTA-Station#223]
# **Если**
Полистать спавнпанель, можно увидеть, что у нас много вещей, которые в игре не задействованы, по сути мелочи, будь то ЧИЗБУРГЕРЫ, пакетики с метом, одежда зимнего типа, и прочее. 

У нас на станции появилось несколько новых автоматов, в которые можно добавлять такие штуки в скрытом виде, как зажигалки зиппо в сигаретном раздатчике, и прочее. Да и расширить контрабанду в техах, ибо она сама по себе очень уныла, и даже за торговца невозможно хорошо поиграть

В общем, шапок и предметов и всякого говна было бы к месту, можно даже в кармашоп добавлять эти плюшки по смешным ценам. Спасибо, дальше мысль уже сложно выражать

**Comment by ITBlackwood** [comment]
>одежда зимнего типа

Лодауты

>Чизбургеры

Готовятся

>пакетики с метом

Крафтятся.

**Comment by ghost** [comment]
ору лол
все тебе принеси
