### ISSUE TITLE
Firelock спрайт.

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#24]
**Описание проблемы**:
Не тот спрайт firelock'а

**Что должно было произойти**: 
Вылезти спрайт firelock'a 

**Что произошло вместо этого**:
Вылез спрайт Гиббера

**Почему это плохо/Какие последствия этого:**
Не слишком важна, но спрайт не подходит

**Детальное описание как повторить возникновение проблемы**:
Нажать ПКМ на закрытый firelock, увидел в пермабриге, за остальные не уверен.

**Comment by BornToKill2** [comment]
Ссылка кстати, http://prnt.sc/etx9lt

**Comment by ITBlackwood** [comment]
Ах да, на случай если кто-то сюда зайдет и спросит себя "Э а че почему не баг?"
Это был странный единичный случай. Вот так вот.
