### ISSUE TITLE
Зекам нужны обнимашки

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#28]
Вот в этом хранилище http://prntscr.com/ev3lab , вот в этих аптечках лежит целых нихуя. Определенно нужно их заполнить, чем-либо ( подходящим содержимым)

**Comment by ITBlackwood** [comment]
Это ващет тонкий намек зекам на то что хуй им а не лекарства :^)

**Comment by ghost** [comment]
если бы они туда еще могли добраться
