### ISSUE TITLE
Транквилизаторы

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#30]
Усыпляющие патроны для дробовика имеют несколько проблем :
1. Они считаются шприцами и в полёте выглядят не как дробь, а как шприцы
2. Не имеют спрайта.
3. Не усыпляют, а лишь накладывают на человека дрожь, и он иногда падает на пару секунд.
4. При выстреле себе в голову не накладывают вообще никакой сонливости.
Нужно:
1.Сделать им хотя бы спрайт.
2. Изменить вещество в шприце и его кол-во.

**Comment by ITBlackwood** [comment]
1. Собственно, ты ожидал что транквилизаторы поставляются дробью? Ну нихуя себе
2. Не имеют какого именно спрайта?
3/5. Хорошо, посмотрю что можно сделать
4. Дядя ты дурак?

**Comment by ITBlackwood** [comment]
Исправил. В реагентах был галоперидол (Оно и понятно впрочем - чтобы стрелять по наркоманам)
Заменил на эфир. 
Спрайты пофиксил.
