### ISSUE TITLE
Трупы выпадают из клон пада 

### ISSUE THREAD

**Issue by KyubeyQB** [ITBlackwood/ATMTA-Station#31]
**Описание проблемы**:
Трупы выпадают из клон пада 

**Что должно было произойти**: 
Ну они не должны выпадать 

**Что произошло вместо этого**:
Труп *барабанная дробь* выпал
**Почему это плохо/Какие последствия этого:**
Насколько важна эта проблема?
Пиздец как важна

**Детальное описание как повторить возникновение проблемы**:
Попробовать клонировать человека, еще есть теория что они выпадают только из апгрейднутого клонера 

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Все, что может нам помочь.
Хз

**Comment by ITBlackwood** [comment]
>>Труп выпал из клонпода
Может это был клон, который скопытился?

**Comment by Dydna** [comment]
Все клоны в таком случае скопычиваются, и им иногда даже дифибы не помогают.
