### ISSUE TITLE
Черные спрайты травы в совятнике 

### ISSUE THREAD

**Issue by KyubeyQB** [ITBlackwood/ATMTA-Station#33]
**Описание проблемы**:
http://imgur.com/a/vVZ7b - После того как сгорит трава.

**Что должно было произойти**: 
Не думаю что черные тайлы это норма

**Детальное описание как повторить возникновение проблемы**:
Я поджег траву

**Comment by ITBlackwood** [comment]
Нахуй ты поджег траву блядь уууууууууууууууууууу сука
:rage4:
