### ISSUE TITLE
Неправильное распределение работы.

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#42]
**Описание проблемы**:
Я стал Д-Классом.

**Что должно было произойти**: 
Я должен был стать клоуном.

**Что произошло вместо этого**:
Я стал Д-Классником.

**Почему это плохо/Какие последствия этого:**
Тебя сразу же отпиздят, а песьман анвайтлистнет

**Детальное описание как повторить возникновение проблемы**:
Поставить в Occupation Preferences работу клоуна на High.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
secret гейммод
http://prnt.sc/f2h250

**Comment by ITBlackwood** [comment]
Велика вероятность что твой клоун мог стать д-классником во время раунда. 
Игра просто заранее расчитала такой исход и закинула тебя в перму :^)

**Comment by ITBlackwood** [comment]
Да и на самом деле такие сбои системы приоритетов есть везде.
Клоз.
