### ISSUE TITLE
Gay-ский под синдиката

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#45]
**Описание проблемы**:
В чем суть проблемы?

**Что должно было произойти**: 
Что должно произойти? Это важно, чтобы понять, баг ли это вообще.

**Что произошло вместо этого**:
Что произошло и насколько это отличается от того, что вы ожидали?

**Почему это плохо/Какие последствия этого:**
Насколько важна эта проблема?

**Детальное описание как повторить возникновение проблемы**:
Это очень важно. Опишите действия, которые, по вашему мнению, привели к багу.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Все, что может нам помочь.

**Comment by ITBlackwood** [comment]
Переоформи
