### ISSUE TITLE
Мех на цк

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#47]
Вот этот мех на цк http://prntscr.com/f4w6kt не работает, в него нельзя влезть. Никому. Даже командиру."Heavy-duty, command-type exosuit. This is a custom model, utilized only by high-ranking military personnel." - гласит его описание, но влезть в него не может никто.

**Comment by ITBlackwood** [comment]
В этот мех могут залазить только с НТ-шным доступом(Не путать с центкомовским), т.е. НТ-офицеры, Главное коммандование. То бишь, те кто даже выше дедсквада. . 
И используется это для ивентов.
