### ISSUE TITLE
[Реквест] Шапки из хвостов

### ISSUE THREAD

**Issue by Godofspace21** [ITBlackwood/ATMTA-Station#51]
Есть на тг операция по отрезанию хвостов у ящуров, с последующим изготовлением из них кожаных шапок. Нужно запилить такую же сюда, но для всех ксеносов (меховые шапки из вульпов, ееее).

**Comment by Dydna** [comment]
Два чая. Нет, три чая этому господину!

**Comment by ITBlackwood** [comment]
Ладно, теперь рассмотрим с технической стороны. 
Для этого придется вводить трём расам новые органы, причем для каждой разные. 
Далее, операции по отрезанию/пришиванию/манипулированию и.т.д
И наконец, крафт из полученных органов предметов. 

И насколько по-вашему часто будет использоваться эта фича? Один? Два раза? 
Делайте выводы.

**Comment by Godofspace21** [comment]
Можно сделать только вульпам. Потому что вульпы.
