### ISSUE TITLE
Тайлы из ресурсов

### ISSUE THREAD

**Issue by Godofspace21** [ITBlackwood/ATMTA-Station#57]
**Описание проблемы**:
Тайлы из различных ресурсов (серебро/золото) не отображаются при установке.

**Что должно было произойти**: 
На тайле пола должна была появится плитка из выбранного материала.

**Что произошло вместо этого**:
Остался спрайт непокрытого пола (+если там установлены трубы/провода, они закрываются).

**Почему это плохо/Какие последствия этого:**
Проблема со спрайтами всегда плохою

**Детальное описание как повторить возникновение проблемы**:
Снять стандартный флуртайл, поставить золотой/серебрянный/любой другой

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Проверялось только на двух указанных выше видах (сер./зол.)

**Comment by ITBlackwood** [comment]
Проверил. Действительно так.

**Comment by ITBlackwood** [comment]
Исправлено
