### ISSUE TITLE
Урон при ловле предметов

### ISSUE THREAD

**Issue by Dankorsar** [ITBlackwood/ATMTA-Station#58]
**Описание проблемы**:
Есть возможность ловить всяческие предметы, начиная от волейбольного мячика до нацеленной в голову плитки. Проблема возникает в том, что предмет-то ловится, но всё равно ударяет по персонажу.

**Что должно было произойти**: 
Выводится строчка о том, что такой-то персонаж ловит то-то. Без нанесения урона.

**Что произошло вместо этого**:
При ловле предмета прилетает урон, будто ты его и не ловил

**Почему это плохо/Какие последствия этого:**
Мягко говоря, странно играть в мячик, когда тебе постоянно прилетает им по еблету. Ну и перехватить летящую в тебя плитку или осколок тоже не помешает иногда.

**Comment by Dydna** [comment]
Можно ввести дамаг только с больших предметов, а маленькие и средние ловить без дамага, если это, конечно, можно сделать

**Comment by ITBlackwood** [comment]
Исправлено
