### ISSUE TITLE
VR Очки

### ISSUE THREAD

**Issue by GreigFreid** [ITBlackwood/ATMTA-Station#60]
Просьба с добавлением VR очков на сервер. Будет отправлять в симуляции. Общий режим устанавливает симуляцию зоны отдыха, режим для детектива симулирует личный офис (А-ля Heavy Rain), а режим для учёного симулирует тестовый полигон для бомб.
![default](https://cloud.githubusercontent.com/assets/28686780/26034028/bebfa97a-38be-11e7-84ee-03ff5735bd82.png)

**Comment by ITBlackwood** [comment]
Они уже постепенно впиливаются
