### ISSUE TITLE
Кукла вуду для чайников, часть первая

### ISSUE THREAD

**Issue by Dankorsar** [ITBlackwood/ATMTA-Station#64]
**Описание проблемы**:
Баловался с куклой вуду. Вставил туда свою карту, подогрел себя пару раз, несколько раз тыкнул кусачками. Потом, когда уточнил, что можно либо карту, либо фотку в неё впихнуть, чтобы поизмываться над жертвами, стал пробовать и ничего не выходило. Даже спецом делал фотки 1х1 и то бестолку было.

**Что должно было произойти**: 
По идее, должен был быть выбор жертвы из тех, кто имеется на фотографии или же чья карта вставлена
**Что произошло вместо этого**:
Описанное выше. Я мог выбрать жертвой только себя, плюс ещё был выбор ещё одной жертвы, карточку которой я заимствовал. И то, после моей карты я в списке выбора жертв остался, а имя вульпаканки - нет.
Вдобавок показывалось аж два места исходящей тёмной силы; одно с направлением, другое с названием отдела
**Почему это плохо/Какие последствия этого:**
Сбой функционала куклы вуду. С редким предметом вот такие странности.
**Детальное описание как повторить возникновение проблемы**:
Собственно, как. Не уверен, что до этого действий не проводилось. Сам я лично запихивал свою карту, попробовал потыкать сначала жигой, потом кусачками и отвёрткой. После пытался запихивать туда фотки 3х3 и 1х1, но результата не давало. Был результат, когда я запихнул карту вульпы, но после того, как я её вытащил, целью был всё равно только я.
**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Вроде ничего подходящего не имеется.

**Comment by ITBlackwood** [comment]
НА самом деле куклой надо ткнуть по жертве
