### ISSUE TITLE
Вульпы

### ISSUE THREAD

**Issue by Doloreere** [ITBlackwood/ATMTA-Station#67]
Сломаны части тела. Будто просто берётся с превьюхи и накладывается поверх. Пруф. Буду чекать, если время сегодня найду. 
![image](https://cloud.githubusercontent.com/assets/22078308/26103830/ee1c6038-3a43-11e7-942c-014e452c784b.png)

**Comment by ITBlackwood** [comment]
В ближайшее время: https://github.com/ParadiseSS13/Paradise/pull/7366
