### ISSUE TITLE
Лом или размер не главное 

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#70]
В общем, ебать, в инженерке на столе лежит ЗДОРОВЫЙ натуральный лом(вроде единственный на станции), но его никто не юзает, потому что ничем кроме размера и чуточки дамага он от карманного не отличается. Предлагаю чтобы им можно было вскрывать аирлоки как джевсами но добавить + 5 секунд. Дискасс.

**Comment by ITBlackwood** [comment]
Пять секунд чего?

**Comment by BigForest** [comment]
Пять секунд ко времени взлома.

**Comment by ITBlackwood** [comment]
Но смысл делать его хуже, если им итак никто не пользуется?

**Comment by Valnaver** [comment]
Ты не понял,он предлагает дать ему код джеммера с вскрытием аирлоков рабочих но повесить него +5 к этому времени.

**Comment by ITBlackwood** [comment]
Хм. Ладно, посмотрим.

**Comment by Dydna** [comment]
И да, он действительно единственный на станции, в пояс и карман его не положить

**Comment by Valnaver** [comment]
А ваобще это не много странно выглядит то что дверь которая проламывает черепа своим закрыванием вскрывается простой фомкой.

**Comment by Dydna** [comment]
Но это не простая фомка, она здоровая, как пельмень

**Comment by ITBlackwood** [comment]
В общем, пришли к мысли что нет, не будем добавлять подобный функционал.
