### ISSUE TITLE
Петля из кабеля, способность повеситься [Реквест]

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#75]
У **Хиппи стейшона** есть в крафте из мотка кабеля петля, чтобы её сделать надо стоять на стуле, столе, как только её сделали, на нее надо перетащить спрайт человека чтобы повеситься. Так же можно вешать других людей.

**Comment by ITBlackwood** [comment]
Интересно. 
Жаль что у нас только ПОТОЛКА НЕТ. ХАХ.

Посмотрю, попробую добавить. Стей тунец.

**Comment by ITBlackwood** [comment]
Посмотрел в код - сложновато для меня. Без помощи не справлюсь.
