### ISSUE TITLE
Пианино

### ISSUE THREAD

**Issue by Artem0410** [ITBlackwood/ATMTA-Station#80]
У пианино есть неудобный момент - настройка ритма. Я думаю, что эту настройку надо сделать удобнее. Например, самому цифрами писать, с какой скоростью будет играть пианино.

**Comment by ITBlackwood** [comment]
Так ведь можно

**Comment by Artem0410** [comment]
Ващет только плюсами и минусами там, а плюс не прибавляет там +1 или тип того, а прибавляет неизвестное число. Из-за чего хочешь поставить на 300, а ставишь на 333.

**Comment by ITBlackwood** [comment]
Меняй в самой песне параметр BPM
