### ISSUE TITLE
Ядра аномалий [Баг]

### ISSUE THREAD

**Issue by MrDiamond320** [ITBlackwood/ATMTA-Station#85]
**Описание проблемы**:
Ядра не выпадают из аномалий

**Что должно было произойти**: 
Ядро аномалии должно выпасть

**Что произошло вместо этого**:
Ядро аномалии не выпало

**Почему это плохо/Какие последствия этого:**
Теряется часть профессии исследователя или просто халявные плюшки ассистонтам в научке

**Детальное описание как повторить возникновение проблемы**:
Дождаться появления аномалии на стейшоне и попытаться её "разминировать" сигналом

**Comment by ITBlackwood** [comment]
Постараюсь заняться

**Comment by ghost** [comment]
@ITBlackwood  40 процентная вероятность ядра сойдет?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/28573306/26553486/4b3b58c6-44a5-11e7-8064-3e5c7c6f286e.png)
собственно хорошие тех уровни за эти ядра

**Comment by ITBlackwood** [comment]
Is gud.
