### ISSUE TITLE
Возможно баг клинера

### ISSUE THREAD

**Issue by Dydna** [ITBlackwood/ATMTA-Station#91]
Если убрать регулятор спейс клинера то выходит 1 тайл вещества(а тратится 10 юнитов) , но с регулятором 2 тайла  и тратися 5 юнитов, следовательно без регулятора должно расходоваться 10 юнитов и 3/4 тайла должна быть струя. Дискасс если я дебил

**Comment by Godofspace21** [comment]
Це фича

**Comment by ITBlackwood** [comment]
не баг.
