### ISSUE TITLE
Федя блять, меня ций говнокод зайибав

### ISSUE THREAD

**Issue by BornToKill2** [ITBlackwood/ATMTA-Station#93]
**ПЫТАЮСЬ СУКА ЗАЙТИ НА КЛОУНА КИДАЕ ВОНО МЕНЕ ЗА ЙИБАНЫХ ДШНИКОВ ШО ЦЕ ТАКЕ ФЕДЯ**

**Comment by ghost** [comment]
охуенное описание.
ты заслужил себе таких багов, пидар

**Comment by ITBlackwood** [comment]
ПАЧИНЕНА
