### ISSUE TITLE
Vortex Anomaly says, "TOO FAST FOR YOU"

### ISSUE THREAD

**Issue by MsCounterMax** [ITBlackwood/ATMTA-Station#95]
**Описание проблемы**:
Вортекс-аномалия превращается в сингу за полминуты, успевая устроить пиздец ВСЕГДА до того, как кто-то успеет с анализатором подойти.

**Что должно было произойти**: 
Она должна была висеть две минуты в пассивном состоянии, потому что даже самый расторопный учёный до неё не успеет дойти.

**Что произошло вместо этого**:
Медбей в щепки.

**Почему это плохо/Какие последствия этого:**
Рандомный хаос на станции с мизерным шансом его избежать, причём разрушения раза в четыре больше чем от метеорита, плюс проёбывается кор аномалии, что вкупе
и с нерфом научки заставляет желать кодерам парадиза мучительной смерти.

**Детальное описание как повторить возникновение проблемы**:
Сидёшь и ждёшь пока не появится вортекс, а как появится можно сразу звать инженеров.

**Что-нибудь еще что может помочь (какой был режим, была ли у вас роль, какие-то особенности и т.д.)**: 
Я РД, вортекс появился в медбее, вот буквально сразу я пошёл за сигналером и как только я подошёл к аномалии она послала меня нахуй и начала жрать медбей.

ФЁДОР ФИКС

**Comment by ghost** [comment]
берешь и хуяришь себя стимуляторами

казул

**Comment by ITBlackwood** [comment]
Лан, ща всё будет

**Comment by ITBlackwood** [comment]
увеличил время в 10 раз.
