### ISSUE TITLE
Невозможность курения сушёных продуктов

### ISSUE THREAD

**Issue by Lianovskiy** [ITBlackwood/ATMTA-Station#97]
**Описание проблемы**:
Сушёные амброзию вульгарис и табак невозможно запихать в трубку и раскурить, трубка выдаёт, что отказывается принимать в себя это.

**Что должно было произойти**: 
Оно должно влазить в трубки (самодельную и заказную) и нормально раскуриваться

**Что произошло вместо этого**:
смотри пункт 1

**Почему это плохо/Какие последствия этого:**
Сушилку клянчили именно для этого!

**Comment by ITBlackwood** [comment]
Не должно. У вас на это бумага для самокруток есть.

**Comment by Lianovskiy** [comment]
Должно, всегда влезало.
