### ISSUE TITLE
Хочу жрать мыло [Баг]

### ISSUE THREAD

**Issue by MrDiamond320** [ITBlackwood/ATMTA-Station#99]
**Описание проблемы**:
Драски не могут жрать мыло,хотя должны и по беку парадайсов,и по вики,хотя технически никто не втупляет,как его жрать

**Что должно было произойти**: 
Мыло должно быть сожрано

**Что произошло вместо этого**:
Драск намыливает себе ебало/Нихуя

**Почему это плохо/Какие последствия этого:**
Теряется особенность Драска,которая может вызвать несколько "Чего блять?" в IC

**Детальное описание как повторить возникновение проблемы**:
Попытаться сожрать мыло за Драска(Тыкнуть там по рту мылом за драска,вилкой потыкать на него)

**Comment by ghost** [comment]
Жрать мыло можно с граб интентом. Закрыто.
